set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_W64_TRIPLE "x86_64-w64-mingw32" CACHE STRING "MinGW-w64 target triple")

set(CMAKE_C_COMPILER "${MINGW_W64_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${MINGW_W64_TRIPLE}-g++")
set(CMAKE_RC_COMPILER "${MINGW_W64_TRIPLE}-windres")

if(EXISTS "/usr/${MINGW_W64_TRIPLE}")
    list(APPEND CMAKE_FIND_ROOT_PATH "/usr/${MINGW_W64_TRIPLE}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
